install.packages('RSQLite')
install.packages('tidyverse')
install.packages('DBI')
install.packages('rmarkdown')
install.packages('ggplot2')
install.packages('DT')
install.packages('janitor')
install.packages('plotly')
install.packages('readr')
install.packages('dplyr')
install.packages('lubridate')
install.packages("rmarkdown")
require(devtools)
install_version("rmarkdown", version = "2.13", repos = "https://cran.r-project.org")
