install.packages('RSQLite')
install.packages('tidyverse')
install.packages('DBI')
install.packages('rmarkdown')
install.packages('ggplot2')
install.packages('DT')
install.packages('janitor')
install.packages('plotly')
install.packages('readr')
install.packages('dplyr')
install.packages('lubridate')
install.packages("rmarkdown")
packageurl <- "https://cran.r-project.org/src/contrib/rmarkdown_2.13.tar.gz"
install.packages(packageurl, repos=NULL, type="source")
