---
title: "Use Case B report example with synthetic data"
author: "Estupiñán-Romero, Francisco; González-Galindo, Javier; Bernal-Delgado, Enrique"
date: "16/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE,
                      out.width = "100%")
```


```{r load_libraries}
## 3. Load required libraries ####
library(tidyverse)
library(DBI)
# library(purrr)
# library(patchwork)
# library(lme4)
# library(glmnet)
# library(MASS)
# library(mgcv)
# library(broom)

```


```{r load_data}
## Write the synthetic dataset as a CSV file

# glimpse(df)

#con <- dbConnect(RSQLite::SQLite(), "/home/phiri/analysis-scripts/inputs/database/database.db")
con <- dbConnect(RSQLite::SQLite(), "c:/temp/phiri_app_pre-alpha/Rmd/mydatabase_syntheticdata.sqlite")
df <- dbReadTable(con, "delayed_ttm_breast_cancer")

```


## Exploratory Analysis (Local)
### Distribution of times from diagnosis of breast cancer to treatment

```{r boxplots}
p_time_dx_to_surgery_nm_period <- 
  df %>% 
  filter(!is.na(time_dx_to_surgery_nm)) %>% 
  ggplot() +
  geom_boxplot(aes(x = period, y = time_dx_to_surgery_nm, group = period)) +
  theme_minimal()

p_time_dx_to_radiotherapy_nm_period <- 
  df %>% 
  filter(!is.na(time_dx_to_radiotherapy_nm)) %>% 
  ggplot() +
  geom_boxplot(aes(x = period, y = time_dx_to_radiotherapy_nm, group = period)) +
  theme_minimal()

p_time_dx_to_chemotherapy_nm_period <- 
  df %>% 
  filter(!is.na(time_dx_to_chemotherapy_nm)) %>% 
  ggplot() +
  geom_boxplot(aes(x = period, y = time_dx_to_chemotherapy_nm, group = period)) +
  theme_minimal()

p_time_dx_to_hormonotherapy_nm_period <- 
  df %>% 
  filter(!is.na(time_dx_to_hormonotherapy_nm)) %>% 
  ggplot() +
  geom_boxplot(aes(x = period, y = time_dx_to_hormonotherapy_nm, group = period)) +
  theme_minimal()

p_time_dx_to_immunotherapy_nm_period <- 
  df %>% 
  filter(!is.na(time_dx_to_immunotherapy_nm)) %>% 
  ggplot() +
  geom_boxplot(aes(x = period, y = time_dx_to_immunotherapy_nm, group = period)) +
  theme_minimal()

p_time_dx_to_surgery_nm_period 

p_time_dx_to_radiotherapy_nm_period 

p_time_dx_to_chemotherapy_nm_period 

p_time_dx_to_hormonotherapy_nm_period 

p_time_dx_to_immunotherapy_nm_period

```


```{r median_times_trends}

p_median_time_dx_to_surgery <- 
  df %>% 
  filter(!is.na(time_dx_to_surgery_nm)) %>% 
  group_by(period) %>% 
  mutate(median_time_to_surgery = median(time_dx_to_surgery_nm, na.rm = TRUE)) %>% 
  ggplot(aes(x = period, y = median_time_to_surgery)) + 
  geom_line() + 
  geom_smooth(method = "loess") +
  geom_vline(aes(xintercept = 27), col = "red", lty = "dashed") + 
  theme_minimal()

p_median_time_dx_to_radiotherapy <- 
  df %>% 
  filter(!is.na(time_dx_to_radiotherapy_nm)) %>% 
  group_by(period) %>% 
  mutate(median_time_to_radiotherapy = median(time_dx_to_radiotherapy_nm, na.rm = TRUE)) %>% 
  ggplot(aes(x = period, y = median_time_to_radiotherapy)) + 
  geom_line() + 
  geom_smooth(method = "loess") +
  geom_vline(aes(xintercept = 27), col = "red", lty = "dashed") + 
  theme_minimal()

p_median_time_dx_to_chemotherapy <- 
  df %>% 
  filter(!is.na(time_dx_to_chemotherapy_nm)) %>% 
  group_by(period) %>% 
  mutate(median_time_to_chemotherapy = median(time_dx_to_chemotherapy_nm, na.rm = TRUE)) %>% 
  ggplot(aes(x = period, y = median_time_to_chemotherapy)) + 
  geom_line() + 
  geom_smooth(method = "loess") +
  geom_vline(aes(xintercept = 27), col = "red", lty = "dashed") + 
  theme_minimal()

p_median_time_dx_to_hormonotherapy <- 
  df %>% 
  filter(!is.na(time_dx_to_hormonotherapy_nm)) %>% 
  group_by(period) %>% 
  mutate(median_time_to_hormonotherapy = median(time_dx_to_hormonotherapy_nm , na.rm = TRUE)) %>% 
  ggplot(aes(x = period, y = median_time_to_hormonotherapy)) + 
  geom_line() + 
  geom_line(method = "loess") +
  geom_vline(aes(xintercept = 27), col = "red", lty = "dashed") + 
  theme_minimal()

p_median_time_dx_to_immunotherapy <- 
  df %>% 
  filter(!is.na(time_dx_to_immunotherapy_nm)) %>% 
  group_by(period) %>% 
  mutate(median_time_to_immunotherapy = median(time_dx_to_immunotherapy_nm , na.rm = TRUE)) %>% 
  ggplot(aes(x = period, y = time_dx_to_immunotherapy_nm)) + 
  geom_line() + 
  geom_line(method = "loess") +
  geom_vline(aes(xintercept = 27), col = "red", lty = "dashed") + 
  theme_minimal()

p_median_time_dx_to_surgery

p_median_time_dx_to_radiotherapy

p_median_time_dx_to_chemotherapy

p_median_time_dx_to_hormonotherapy

p_median_time_dx_to_immunotherapy

```


```{r}

df_period <- 
  df %>% 
  group_by(period) %>% 
  summarise(
    period = unique(period),
    country_cd = unique(country_cd),
    median_age = median(age_nm, na.rm = TRUE),
    iqr_age = IQR(age_nm, na.rm = TRUE),
    sd_age = sd(age_nm, na.rm = TRUE), 
    prop_low_socecon_lvl = sum(socecon_lvl_cd)/nrow(.),
    median_time_to_surgery = median(time_dx_to_surgery_nm, na.rm = TRUE),
    median_time_to_radio = median(time_dx_to_radiotherapy_nm, na.rm = TRUE),
    median_time_to_chemo = median(time_dx_to_chemotherapy_nm, na.rm = TRUE),
    median_time_to_hormones = median(time_dx_to_hormonotherapy_nm, na.rm = TRUE),
    iqr_time_to_surgery = IQR(time_dx_to_surgery_nm, na.rm = TRUE),
    iqr_time_to_radio = IQR(time_dx_to_radiotherapy_nm, na.rm = TRUE),
    iqr_time_to_chemo = IQR(time_dx_to_chemotherapy_nm, na.rm = TRUE),
    iqr_time_to_hormones = IQR(time_dx_to_hormonotherapy_nm, na.rm = TRUE))

write_csv(df_period, file = "aggregated_outputs.csv")

```

