---
title: "Use Case B report example with synthetic data"
author: "Estupiñán-Romero, Francisco; González-Galindo, Javier; Bernal-Delgado, Enrique"
date: "16/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE,
                      out.width = "100%")
```


```{r load_libraries}
## 3. Load required libraries ####
library(tidyverse)
library(DBI)
# library(purrr)
# library(patchwork)
# library(lme4)
# library(glmnet)
# library(MASS)
# library(mgcv)
# library(broom)

```


```{r load_data}
## Write the synthetic dataset as a CSV file

# glimpse(df)

#con <- dbConnect(RSQLite::SQLite(), "/home/phiri/analysis-scripts/inputs/database/database.db")
con <- dbConnect(RSQLite::SQLite(), "../UseCaseB/mydatabase_syntheticdata.sqlite")
df <- dbReadTable(con, "delayed_ttm_breast_cancer")

```


## Exploratory Analysis (Local)
### Distribution of times from diagnosis of breast cancer to treatment

```{r boxplots}
p_time_dx_to_surgery_nm_period <- 
  df %>% 
  filter(!is.na(time_dx_to_surgery_nm)) %>% 
  ggplot() +
  geom_boxplot(aes(x = period, y = time_dx_to_surgery_nm, group = period)) +
  theme_minimal()

p_time_dx_to_radiotherapy_nm_period <- 
  df %>% 
  filter(!is.na(time_dx_to_radiotherapy_nm)) %>% 
  ggplot() +
  geom_boxplot(aes(x = period, y = time_dx_to_radiotherapy_nm, group = period)) +
  theme_minimal()

p_time_dx_to_chemotherapy_nm_period <- 
  df %>% 
  filter(!is.na(time_dx_to_chemotherapy_nm)) %>% 
  ggplot() +
  geom_boxplot(aes(x = period, y = time_dx_to_chemotherapy_nm, group = period)) +
  theme_minimal()

p_time_dx_to_hormonotherapy_nm_period <- 
  df %>% 
  filter(!is.na(time_dx_to_hormonotherapy_nm)) %>% 
  ggplot() +
  geom_boxplot(aes(x = period, y = time_dx_to_hormonotherapy_nm, group = period)) +
  theme_minimal()

p_time_dx_to_immunotherapy_nm_period <- 
  df %>% 
  filter(!is.na(time_dx_to_immunotherapy_nm)) %>% 
  ggplot() +
  geom_boxplot(aes(x = period, y = time_dx_to_immunotherapy_nm, group = period)) +
  theme_minimal()

p_time_dx_to_surgery_nm_period 

p_time_dx_to_radiotherapy_nm_period 

p_time_dx_to_chemotherapy_nm_period 

p_time_dx_to_hormonotherapy_nm_period 

p_time_dx_to_immunotherapy_nm_period

```


